# Change these first
owner: Data-Innova # Your GitHub organization or username, where this repository lives
repo: monitoreo-compliance # The name of this repository

sites:
  - name: Compliance - Batch
    url: https://app.compliance.com.co/validador/healthBatch/healthChecks/health
  - name: Compliance - Web
    url: https://app.compliance.com.co/validador/apiPublica/healthChecks
  - name: Compliance - WebService
    url: https://app.compliance.com.co/validador/healthWs/healthChecks
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /monitoreo-compliance
  logoUrl: https://validador.compliance.com.co/assets/images/favicon-compliance.png
  name: Compliance - Status
  introTitle: "Servicios de Compliance, powered entirely by GitHub."
  introMessage: Status de servicios generales de [Compliance](https://www.compliance.com.co/).
  navbar:
    - title: Status
      href: /

workflowSchedule:
  graphs: "0 5 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 5 * * *"
  summary: "0 5 * * *"
  updateTemplate: "0 5 * * *"
  updates: "0 5 * * *"
  uptime: "*/2 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
